atividade_final_pt1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rede_social.urls'))
]

rede_social/urls.py
from django.urls import path

from rede_social.views import index, perfil_template

urlpatterns = [
    path('', index, name="index"),
    path('perfil/<str:slug>/', perfil_template, name='perfil')
]

rede_social/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Pessoa(models.Model):
    nome = models.CharField('Nome', max_length=50)

    slug = models.SlugField('Slug', max_length=250)

    usuario = models.OneToOneField(
        User, 
        on_delete=models.CASCADE, 
        verbose_name='Usuário')
    
    amigos = models.ManyToManyField('Pessoa', blank=True)

    def __str__(self):
        return self.nome
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)
        super(Pessoa, self).save(*args, **kwargs)


class Postagem(models.Model):

  pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, verbose_name="Usuario" )

  conteudo = models.CharField('Conteudo', max_length=200)

  data = models.DateTimeField("Data de publicação", auto_now_add=True)

  def __str__(self):
    return self.conteudo

class Comentario(models.Model):

  pessoa = models.ForeignKey(Pessoa, on_delete=models.CASCADE, verbose_name="Usuario")
  postagem = models.ForeignKey(Postagem, on_delete=models.CASCADE, verbose_name="Postagens")
  conteudo = models.CharField('Comentario', max_length=200)
  data = models.DateTimeField("Data de publicação", auto_now_add=True)
  
  def __str__(self):
     return self.conteudo

rede_social/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render
from django.db.models import Prefetch

from .models import Pessoa, Postagem

def index(request):
  return HttpResponse('Página Inicial')

def perfil_template(request,slug):
  try:
    perfil = Pessoa.objects.prefetch_related(
      Prefetch('postagem_set', queryset=Postagem.objects.order_by('-data'))
    ).get(slug=slug)

  except Pessoa.DoesNotExist:
    raise Http404('Perfil não encontrado')
    
  return render(request, 'rede_social/perfil.html', {'perfil': perfil})

rede_social/templates/rede_social/perfil.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Atividade Final de Daoc</title>

    <link
      rel="canonical"
      href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/"
    />

    <!-- Bootstrap core CSS -->
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Favicons -->
    <meta name="theme-color" content="#012D76" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link
      href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/offcanvas.css"
      rel="stylesheet"
    />
  </head>
  <body class="bg-light">
    <nav
      class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark"
      aria-label="Main navigation"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="#">BLOGZÃO DO CEULP</a>
        <button
          class="navbar-toggler p-0 border-0"
          type="button"
          id="navbarSideCollapse"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="navbar-collapse offcanvas-collapse"
          id="navbarsExampleDefault"
        ></div>
      </div>
    </nav>

    <div class="d-flex align-items-center p-2 my-2 shadow-sm">
       <p class="pb-2 mb-0 medium lh-sm">Atividade Final de Daoc</p>
    </div>

    <main class="container">
      <div
        class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm"
      >
        <div class="lh-1">
          <p class="pb-2 mb-0 medium lh-sm">Olá, bem vindo(a) ao meu blog, me chamo </p>
          <h1 class="h4 mb-0 text-white lh-1">{{ perfil.nome }}</h1>
        </div>
      </div>

      <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-4 mb-0">Postagens</h6>
        {% for postagem in perfil.postagem_set.all %}
        <div class="d-flex pt-3">
          <p class="pb-3 mb-0 big lh-sm">{{ postagem.conteudo }}</p>
        </div>
        <div class="d-flex pt-4">
          {% for comentario in postagem.comentario_set.all %}
          <p class="pb-4 mb-0 small text-muted lh-sm"> {{ comentario.pessoa.nome }} comentou {{ comentario }}</p>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
    </main>

    <script
      src="/docs/5.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <script src="offcanvas.js"></script>
  </body>
</html>